---
- import_tasks: install.yml
  tags: docker:install
  
- import_tasks: prepare.yml
  tags: docker:prepare

- import_tasks: secrets.yml
  tags: docker:secrets

- import_tasks: network.yml
  tags: docker:network

- import_tasks: stack.yml
  tags: docker:stack

- import_tasks: users.yml
  tags: docker:users

- import_tasks: cleanup.yml
  tags: docker:cleanup
